### ISSUE TITLE
clearing localstorage option, or no auto-replay

### ISSUE THREAD

**Issue by edtechdev** [alecperkins/coffeetable#14]
I entered document.write("hello") which overwrote the page.  But since it automatically stores the code and replays it, the page was no longer visible.  Until I manually deleted the row from localstorage using chrome's javascript console.
Perhaps just load the last typed line in the textbox without actually executing it.

**Comment by alecperkins** [comment]
The widget can be programmatically cleared, using `CoffeeTable.clear()` in the regular console, even if you blank the page. It's also possible to pass the widget options when it's included in the page that disable the auto-replay and the use of localStorage.

Personally I prefer having the replay be the default, but since it's just a click away it's not a big deal if it isn't. More importantly, I can imagine situations where it'd be an actual problem if the history were replayed accidentally, whereas the lack of auto-replay is at most a trivial-annoyance.

**Comment by edtechdev** [comment]
document.write("hello") completely clears the page, there is no more coffeetable button or console. 
I'm just letting you know since visitors may accidentally bork your webpage, and reloading the page doesn't fix it since it is constantly replayed from localstorage.

**Comment by alecperkins** [comment]
Right, but all the scripts are still loaded in memory, so it can be programmatically cleared through the built-in console of the browser. I do agree though that the default shouldn't be auto-replay, especially in case the command is more destructive than simply blanking the page.
